### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by theBowja** [Nohminist/resleri#1]
Hi. How do you get your data source? I am looking for English details of character, memoria, etc.

**Comment by Nohminist** [comment]
Hi,

Thank you for your inquiry.

I got the data from playing the game normally. I did not use any analysis tools or official sources.

I found this site and I would like to introduce it to you. It has the English version of the data for the characters and memoria.

https://docs.google.com/spreadsheets/d/e/2PACX-1vSayrK_YAAhU5oGVh6KR3C_7-xDwB56ZxscgdqMuY2yYZB7Hp2liAeDsAis693nTop7UGFMKOxTyIkS/pubhtml#

I hope this helps. If you have any other questions, please feel free to contact me.

Best regards,

**Comment by theBowja** [comment]
hmm thanks
